target_link_libraries(viewshell PUBLIC nlohmann_json::nlohmann_json tl::expected)

if(WIN32)
  find_path(WEBVIEW2_INCLUDE_DIR WebView2.h)
  find_library(WEBVIEW2_LIBRARY NAMES WebView2LoaderStatic WebView2Loader)

  if(WEBVIEW2_INCLUDE_DIR AND WEBVIEW2_LIBRARY)
    target_include_directories(viewshell PRIVATE ${WEBVIEW2_INCLUDE_DIR})
    target_link_libraries(viewshell PRIVATE ${WEBVIEW2_LIBRARY})
    target_compile_definitions(viewshell PRIVATE VIEWSHELL_HAS_WEBVIEW2=1)
  else()
    message(STATUS "WebView2 SDK not found; Windows webview support will be disabled")
    target_compile_definitions(viewshell PRIVATE VIEWSHELL_HAS_WEBVIEW2=0)
  endif()

  target_link_libraries(viewshell PRIVATE ole32 user32)
else()
  pkg_check_modules(GTK3 REQUIRED gtk+-3.0)
  pkg_check_modules(X11 REQUIRED x11)
  target_include_directories(viewshell PRIVATE ${GTK3_INCLUDE_DIRS} ${X11_INCLUDE_DIRS})
  target_link_libraries(viewshell PRIVATE ${GTK3_LIBRARIES} ${X11_LIBRARIES})
  target_compile_options(viewshell PRIVATE ${GTK3_CFLAGS_OTHER} ${X11_CFLAGS_OTHER})

  pkg_check_modules(WEBKITGTK41 QUIET webkit2gtk-4.1)
  if(WEBKITGTK41_FOUND)
    target_include_directories(viewshell PRIVATE ${WEBKITGTK41_INCLUDE_DIRS})
    target_link_libraries(viewshell PRIVATE ${WEBKITGTK41_LIBRARIES})
    target_compile_options(viewshell PRIVATE ${WEBKITGTK41_CFLAGS_OTHER})
  else()
    pkg_check_modules(WEBKITGTK40 REQUIRED webkit2gtk-4.0)
    target_include_directories(viewshell PRIVATE ${WEBKITGTK40_INCLUDE_DIRS})
    target_link_libraries(viewshell PRIVATE ${WEBKITGTK40_LIBRARIES})
    target_compile_options(viewshell PRIVATE ${WEBKITGTK40_CFLAGS_OTHER})
  endif()
endif()
